export const dayTimeData = [
  [
    { label: '18', value: 'yesterday' },
    { label: '19', value: 'yesterday' },
    { label: '20', value: 'yesterday' },
    { label: '21', value: 'yesterday' },
    { label: '22', value: 'yesterday' },
    { label: '23', value: 'yesterday' },
    { label: '00', value: 'today' },
    { label: '01', value: 'today' },
    { label: '02', value: 'today' },
    { label: '03', value: 'today' },
    { label: '04', value: 'today' },
    { label: '05', value: 'today' },
    { label: '06', value: 'today' },
    { label: '07', value: 'today' },
    { label: '08', value: 'today' },
    { label: '09', value: 'today' },
    { label: '10', value: 'today' },
    { label: '11', value: 'today' },
    { label: '12', value: 'today' },
    { label: '13', value: 'today' },
    { label: '14', value: 'today' },
    { label: '15', value: 'today' },
    { label: '16', value: 'today' },
    { label: '17', value: 'today' },
    { label: '18', value: 'today' },
    { label: '19', value: 'today' },
    { label: '20', value: 'today' },
    { label: '21', value: 'today' },
    { label: '22', value: 'today' },
    { label: '23', value: 'today' },
  ],
  [
    { label: '00', value: '' },
    { label: '05', value: '' },
    { label: '10', value: '' },
    { label: '15', value: '' },
    { label: '20', value: '' },
    { label: '25', value: '' },
    { label: '30', value: '' },
    { label: '35', value: '' },
    { label: '40', value: '' },
    { label: '45', value: '' },
    { label: '50', value: '' },
    { label: '55', value: '' },
  ],
];
